apiVersion: v1
kind: Service
metadata:
  name: devops-exercise-service
spec:
  selector:
    app: devops-exercise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
